# Generated by Django 3.2.6 on 2021-09-13 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lectores',
            fields=[
                ('id_lector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fecha', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.lectores')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.metodo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('nombre', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('sinopsis', models.CharField(max_length=300)),
                ('anio', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.autor')),
            ],
        ),
        migrations.AddField(
            model_name='lectores',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.sexo'),
        ),
        migrations.AddField(
            model_name='lectores',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_genero', models.CharField(max_length=50)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id_formato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_formato', models.CharField(max_length=50)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id_detalle_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.libro')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectores.pedido')),
            ],
        ),
    ]
